// @ts-nocheck
/**
 * Plugin Registry Provider 插件 — 插件注册表和搜索服务，可独立加载/卸载/热替换。
 *
 * 提供完整的插件元数据（包含 provides/inject 依赖关系、tags 类型标签、
 * core/locked 核心保护标记、riskLevel 风险等级），供 PluginManager 使用。
 */
import type { Plugin } from '../cordis/src/index.ts'

/**
 * 模块级常量：所有已知插件的元数据列表。
 * 在模块加载时即可用，不依赖 Cordis fiber 激活时序。
 */
const KNOWN_PLUGINS = [
    // ===== 核心系统插件（不可关闭） =====
    { name: '@codem/slots', version: '1.0.0', description: 'Slot Registry — UI 插件槽位注册系统，所有 UI 插件的基础设施', provides: ['slots'], inject: [], keywords: ['slots', 'registry', 'ui'], category: 'core', tags: ['infra', 'ui'], core: true, locked: true, icon: '🧩', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭将导致所有 UI 插件失效，界面无法正常渲染' },

    // ===== Core Service Providers（核心服务） =====
    { name: '@codem/llm', version: '1.0.0', description: 'LLM Service — 大语言模型调用服务，Agent 的核心推理能力', provides: ['llm'], inject: [], keywords: ['llm', 'ai'], category: 'provider', tags: ['service', 'agent'], hot: true, icon: '🤖', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后 Agent 将无法进行推理和生成回复，所有对话功能不可用' },
    { name: '@codem/tools', version: '1.0.0', description: 'Tools Service — 工具注册和调用服务，Agent 执行操作的能力', provides: ['tools'], inject: [], keywords: ['tools'], category: 'provider', tags: ['service', 'tool'], hot: true, icon: '🔧', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后 Agent 将无法调用任何工具（文件读写、命令执行等）' },
    { name: '@codem/session', version: '1.0.0', description: 'Session Service — 会话管理服务，维护对话上下文和状态', provides: ['session'], inject: [], keywords: ['session'], category: 'provider', tags: ['service', 'storage'], hot: true, icon: '💬', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后无法创建或恢复会话，对话历史将丢失' },
    { name: '@codem/storage', version: '1.0.0', description: 'Storage Service — 持久化存储服务，配置和数据的保存', provides: ['storage'], inject: [], keywords: ['storage'], category: 'provider', tags: ['service', 'storage'], hot: true, icon: '💾', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后所有设置和数据无法持久化，重启后恢复默认' },
    { name: '@codem/memory', version: '1.0.0', description: 'Memory Service — 记忆管理服务，跨会话的知识保留', provides: ['memory'], inject: [], keywords: ['memory'], category: 'provider', tags: ['service', 'storage'], hot: true, icon: '🧠', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后 Agent 将无法记忆跨会话信息，每次对话从零开始' },
    { name: '@codem/permission', version: '1.0.0', description: 'Permission Service — 权限控制服务，工具调用的安全审批', provides: ['permission'], inject: [], keywords: ['permission'], category: 'provider', tags: ['service', 'security'], hot: true, icon: '🔐', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后工具调用将跳过权限检查，存在安全风险' },
    { name: '@codem/mcp', version: '1.0.0', description: 'MCP Service — Model Context Protocol 工具协议服务', provides: ['mcp'], inject: [], keywords: ['mcp'], category: 'provider', tags: ['service', 'tool', 'bridge'], hot: true, icon: '🔌', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后无法使用 MCP 协议的第三方工具' },
    { name: '@codem/skill', version: '1.0.0', description: 'Skill Service — 技能注册服务，Agent 的技能库', provides: ['skill'], inject: [], keywords: ['skill'], category: 'provider', tags: ['service', 'agent'], hot: true, icon: '⚡', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后 Agent 将无法使用技能（预定义的提示词模板）' },
    { name: '@codem/subagent', version: '1.0.0', description: 'Subagent Service — 子代理管理服务，多 Agent 编排', provides: ['subagent'], inject: [], keywords: ['subagent'], category: 'provider', tags: ['service', 'agent'], hot: true, icon: '👥', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后无法创建子 Agent，多智能体协同功能不可用' },
    { name: '@codem/settings', version: '1.0.0', description: 'Settings Service — 设置管理服务，全局配置', provides: ['settings'], inject: [], keywords: ['settings'], category: 'provider', tags: ['service'], hot: true, icon: '⚙️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后无法读取或保存应用设置' },
    { name: '@codem/theme', version: '1.0.0', description: 'Theme Service — 主题管理服务，UI 外观切换', provides: ['theme'], inject: [], keywords: ['theme'], category: 'provider', tags: ['service', 'ui'], hot: true, icon: '🎨', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后主题切换不可用，界面恢复默认样式' },

    // ===== Capability Providers（能力实现） =====
    { name: '@codem/fs-local', version: '1.0.0', description: 'Local FileSystem Provider — 本地文件系统读写', provides: ['fs'], inject: [], keywords: ['fs', 'file'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '📁', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后 Agent 无法读写文件，文件相关工具全部失效' },
    { name: '@codem/shell-local', version: '1.0.0', description: 'Local Shell Provider — 本地命令行执行', provides: ['shell'], inject: [], keywords: ['shell'], category: 'provider', tags: ['provider', 'runtime'], hot: true, icon: '🖥️', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后 Agent 无法执行命令行操作（编译、安装、运行等）' },
    { name: '@codem/sandbox-local', version: '1.0.0', description: 'Sandbox Provider — 沙箱隔离执行环境', provides: ['sandbox'], inject: ['shell'], keywords: ['sandbox'], category: 'provider', tags: ['provider', 'security'], hot: true, icon: '📦', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后沙箱执行环境不可用，代码运行将在直接本地执行', status: 'active' },
    { name: '@codem/web-search', version: '1.0.0', description: 'Web Search Provider — 网页搜索服务', provides: ['web'], inject: [], keywords: ['web', 'search'], category: 'provider', tags: ['provider'], hot: true, icon: '🔍', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Agent 无法进行网页搜索' },
    { name: '@codem/compaction', version: '1.0.0', description: 'Compaction Provider — 上下文压缩服务，自动裁剪长对话', provides: ['compaction'], inject: [], keywords: ['compaction'], category: 'provider', tags: ['provider'], hot: true, icon: '✂️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后长对话无法自动压缩，可能导致 token 溢出' },
    { name: '@codem/hooks', version: '1.0.0', description: 'Hooks Provider — 钩子事件服务，生命周期回调', provides: ['hooks'], inject: [], keywords: ['hooks'], category: 'provider', tags: ['provider'], hot: true, icon: '🪝', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后生命周期钩子不可用' },
    { name: '@codem/approval', version: '1.0.0', description: 'Approval Provider — 审批服务，关键操作的人工确认', provides: ['approval'], inject: [], keywords: ['approval'], category: 'provider', tags: ['provider', 'security'], hot: true, icon: '✅', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后关键操作将跳过人工审批，存在安全风险' },
    { name: '@codem/permissions', version: '1.0.0', description: 'Permissions Provider — 权限策略服务，细粒度访问控制', provides: ['permissions'], inject: [], keywords: ['permissions'], category: 'provider', tags: ['provider', 'security'], hot: true, icon: '🛡️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后细粒度权限策略不可用' },
    { name: '@codem/automation', version: '1.0.0', description: 'Automation Provider — 自动化执行服务', provides: ['automation'], inject: [], keywords: ['automation'], category: 'provider', tags: ['provider'], hot: true, icon: '🤖', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后自动化任务触发器不可用' },

    // ===== P6 Providers（扩展能力） =====
    { name: '@codem/identity', version: '1.0.0', description: 'Identity Provider — 身份认证服务', provides: ['identity'], inject: [], keywords: ['identity'], category: 'provider', tags: ['provider', 'security'], icon: '🪪', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后身份认证不可用', status: 'active' },
    { name: '@codem/lsp', version: '1.0.0', description: 'LSP Provider — 语言服务器协议，代码智能提示', provides: ['lsp'], inject: [], keywords: ['lsp'], category: 'provider', tags: ['provider', 'tool'], icon: '📄', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后代码补全和诊断不可用' },
    { name: '@codem/code-runtime', version: '1.0.0', description: 'Code Runtime Provider — 代码运行时，执行代码片段', provides: ['codeRuntime'], inject: [], keywords: ['code', 'runtime'], category: 'provider', tags: ['provider', 'runtime'], icon: '🏃', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后代码片段直接运行功能不可用' },
    { name: '@codem/workflow', version: '1.0.0', description: 'Workflow Provider — 工作流引擎，多步骤任务编排', provides: ['workflow'], inject: [], keywords: ['workflow'], category: 'provider', tags: ['provider', 'agent'], icon: '🔄', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后工作流编排功能不可用' },
    { name: '@codem/context-info', version: '1.0.0', description: 'Context Info Provider — 上下文信息收集', provides: ['contextInfo'], inject: ['settings'], keywords: ['context'], category: 'provider', tags: ['provider'], icon: '📋', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后上下文信息收集不可用', status: 'active' },
    { name: '@codem/commands', version: '1.0.0', description: 'Commands Provider — 命令注册服务，快捷操作', provides: ['commands'], inject: ['skill'], keywords: ['commands'], category: 'provider', tags: ['provider', 'tool'], icon: '⌘', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后自定义命令快捷操作不可用', status: 'active' },
    { name: '@codem/user-questions', version: '1.0.0', description: 'User Questions Provider — 用户提问服务，Agent 主动询问', provides: ['userQuestions'], inject: [], keywords: ['questions'], category: 'provider', tags: ['provider', 'agent'], icon: '❓', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后 Agent 无法主动向用户提问，交互体验降级' },
    { name: '@codem/notebook', version: '1.0.0', description: 'Notebook Provider — 笔记本服务，知识管理', provides: ['notebook'], inject: [], keywords: ['notebook'], category: 'provider', tags: ['provider', 'storage'], icon: '📓', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后笔记本功能不可用' },
    { name: '@codem/squad', version: '1.0.0', description: 'Squad Provider — 多智能体编排，Agent 团队协作', provides: ['squad'], inject: [], keywords: ['squad'], category: 'provider', tags: ['provider', 'agent'], icon: '🎯', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后多智能体团队协作功能不可用' },
    { name: '@codem/dynamic-runner', version: '1.0.0', description: 'Dynamic Runner Provider — 动态运行器，运行时代码执行', provides: ['dynamicCordisRunner'], inject: [], keywords: ['runner'], category: 'provider', tags: ['provider', 'runtime'], icon: '⚡', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后动态运行器不可用', status: 'active' },
    { name: '@codem/plugin-registry', version: '1.0.0', description: 'Plugin Registry Provider — 插件注册表服务，插件市场的数据源', provides: ['pluginRegistry'], inject: [], keywords: ['registry'], category: 'core', tags: ['infra', 'service'], icon: '📜', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后插件市场将无法显示插件列表和搜索', status: 'active' , uiImpact: { buttons: ["plugin-manager"], degradedTo: '插件管理按钮不显示' }},

    // ===== dsh 兼容层 =====
    { name: '@codem/dsh-compat', version: '1.0.0', description: 'DeepSeek Harness Compatibility Layer — dsh 插件兼容适配层，使 dsh 插件可在 Codem 中运行', provides: ['dshLLM', 'dshShell', 'dshFS', 'dshTools'], inject: ['llm', 'shell', 'fs', 'tools'], keywords: ['dsh', 'compat'], category: 'compat', tags: ['bridge'], icon: '🔗', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 dsh (DeepSeek Harness) 插件将无法运行' },

    // ===== R1 Providers (从 bridge-plugin.ts 迁移) =====
    { name: '@codem/guard', version: '1.0.0', description: 'Guard Provider — 工具调用去重和截止时间检查，防止 Agent 循环', provides: ['guard'], inject: [], keywords: ['guard', 'dedup'], category: 'provider', tags: ['provider', 'security'], icon: '🛡️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后工具调用去重不可用，Agent 可能重复调用相同工具', status: 'active', optionalInject: ['repeatToolReminder'] },
    { name: '@codem/credentials', version: '1.0.0', description: 'Credentials Provider — API key 和密钥管理服务', provides: ['credentials'], inject: [], keywords: ['credentials', 'api-key'], category: 'provider', tags: ['provider', 'security'], icon: '🔑', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后 API key 管理不可用，LLM Provider 无法获取密钥', status: 'active' },
    { name: '@codem/attachments', version: '1.0.0', description: 'Attachments Provider — 内容寻址附件存储服务', provides: ['attachments'], inject: [], keywords: ['attachments', 'content'], category: 'provider', tags: ['provider', 'storage'], icon: '📎', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后附件内容寻址存储不可用', status: 'active' },
    { name: '@codem/schedule', version: '1.0.0', description: 'Schedule Provider — 定时提醒和调度服务', provides: ['schedule'], inject: ['inbox'], keywords: ['schedule', 'reminder'], category: 'provider', tags: ['provider', 'automation'], icon: '⏰', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后定时提醒不可用', status: 'active' },
    { name: '@codem/plans', version: '1.0.0', description: 'Plans Provider — 结构化任务计划管理，步骤跟踪和持久化', provides: ['plans'], inject: [], keywords: ['plans', 'steps'], category: 'provider', tags: ['provider', 'agent'], icon: '📝', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后结构化计划管理不可用，步骤进度不持久化', status: 'active' },
    { name: '@codem/preset', version: '1.0.0', description: 'Preset Provider — 配置预设管理，批量设置加载/保存', provides: ['preset'], inject: [], keywords: ['preset', 'config'], category: 'provider', tags: ['provider'], icon: '🎛️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后配置预设不可用', status: 'active' },
    { name: '@codem/host-client', version: '1.0.0', description: 'Host/Client Provider — 多端协同架构基础（Bundle/SDK/ACP/Host/Client/Installer）', provides: ['bundle', 'sdk', 'acp', 'host', 'client', 'pluginInstaller'], inject: [], keywords: ['host', 'client', 'rpc', 'remote'], category: 'provider', tags: ['provider', 'infra'], icon: '🌐', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后多端协同和插件安装功能不可用', status: 'active' },

    // ===== UI 插件 =====
    { name: '@codem/ui-sidebar', version: '1.0.0', description: 'Sidebar UI Plugin — 侧边栏界面，导航和项目管理', provides: [], inject: ['slots'], slots: ['app.sidebar'], keywords: ['ui', 'sidebar'], category: 'ui', tags: ['ui'], icon: '📋', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后侧边栏消失，无法导航到项目、设置等' , uiImpact: { slots: ["app.sidebar"], degradedTo: 'fallback Sidebar (内联组件)' }},
    { name: '@codem/ui-conversation', version: '1.0.0', description: 'Conversation UI Plugin — 对话面板，Agent 交互主界面', provides: [], inject: ['slots'], slots: ['app.conversation'], keywords: ['ui', 'conversation'], category: 'ui', tags: ['ui'], icon: '💬', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后对话面板消失，无法与 Agent 交互' , uiImpact: { slots: ["app.conversation"], degradedTo: 'fallback ChatPanel (内联组件)' }},
    { name: '@codem/ui-tool', version: '1.0.0', description: 'Tool UI Plugin — 工具调用详情面板', provides: [], inject: ['slots'], slots: ['conversation.details.tool'], keywords: ['ui', 'tool'], category: 'ui', tags: ['ui', 'tool'], icon: '🔨', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后工具调用详情不显示，但不影响工具执行' , uiImpact: { slots: ["conversation.details.tool"], degradedTo: 'fallback ToolRenderer (内联组件)' }},
    { name: '@codem/ui-settings', version: '1.0.0', description: 'Settings UI Plugin — 设置面板，全局配置界面', provides: [], inject: ['slots'], slots: ['app.settings'], keywords: ['ui', 'settings'], category: 'ui', tags: ['ui'], icon: '⚙️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后设置面板不可用，无法修改配置' , uiImpact: { slots: ["app.settings"], degradedTo: 'fallback SettingsPanel (内联组件)' }},
    { name: '@codem/ui-misc', version: '1.0.0', description: 'Misc UI Plugin — 杂项 UI 组件（Monitor、Overlay 等）', provides: [], inject: ['slots'], slots: ['app.overlay', 'app.monitor'], keywords: ['ui', 'misc'], category: 'ui', tags: ['ui'], icon: '🧪', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后部分辅助 UI 组件不显示' , uiImpact: { slots: ["app.overlay","app.monitor"], buttons: ["cicd","perf"], degradedTo: 'CI/CD 和性能面板按钮隐藏' }},
    { name: '@codem/ui-market', version: '1.0.0', description: 'Market UI Plugin — 插件市场 UI（Skill/MCP/Plugin 管理器）', provides: [], inject: ['slots'], slots: ['app.skill-manager', 'app.mcp-manager', 'app.plugin-manager'], keywords: ['ui', 'market'], category: 'ui', tags: ['ui'], icon: '🏪', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后插件市场、技能管理、MCP 管理界面不可用' , uiImpact: { slots: ["app.skill-manager","app.mcp-manager","app.plugin-manager"], degradedTo: '管理器面板不可打开' }},
    { name: '@codem/ui-theme', version: '1.0.0', description: 'Theme UI Plugin — 主题插件，暗色/亮色切换', provides: [], inject: [], keywords: ['theme'], category: 'ui', tags: ['ui'], icon: '🎨', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后主题切换 UI 不可用' , uiImpact: { panels: ["theme-switcher"], degradedTo: '主题切换不可用' }},
    { name: '@codem/ui-skin-default', version: '1.0.0', description: 'Default Skin Plugin — 默认皮肤配色方案', provides: [], inject: [], keywords: ['skin', 'default'], category: 'ui', tags: ['ui', 'theme'], icon: '🎨', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后默认配色不可用，界面恢复浏览器默认样式' , uiImpact: { panels: ["skin-default"], degradedTo: '浏览器默认样式' }},
    { name: '@codem/ui-skin-pet', version: '1.0.0', description: 'Pet Skin Plugin — 宠物皮肤配色变体', provides: [], inject: [], keywords: ['skin', 'pet'], category: 'ui', tags: ['ui', 'theme'], icon: '🐱', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后宠物皮肤不可用' , uiImpact: { panels: ["skin-pet"], degradedTo: '默认皮肤替代' }},
    { name: '@codem/ui-pet', version: '1.0.0', description: 'Pet Overlay UI Plugin — 宠物覆盖层 UI 组件', provides: [], inject: ['slots'], slots: ['app.overlay'], keywords: ['pet', 'overlay'], category: 'ui', tags: ['ui'], icon: '🐾', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后宠物覆盖层不显示' , uiImpact: { slots: ["app.overlay"], degradedTo: '宠物覆盖层不显示' }},

    // ===== R4 Providers (AgenticLoop 迁移到 ctx 消费) =====
    { name: '@codem/vision-proxy', version: '1.0.0', description: 'Vision Proxy Provider — 视觉代理服务，图像理解和多模态处理', provides: ['visionProxy'], inject: [], keywords: ['vision', 'proxy', 'multimodal'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '👁️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后图像理解功能不可用' },
    { name: '@codem/message-storage', version: '1.0.0', description: 'Message Storage Provider — 消息持久化存储，对话历史管理', provides: ['messageStorage'], inject: [], keywords: ['message', 'storage'], category: 'core', tags: ['provider', 'storage'], hot: true, icon: '📦', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后对话历史无法持久化，重启后丢失所有消息' },
    { name: '@codem/event-log', version: '1.0.0', description: 'Event Log Provider — 事件日志服务，系统行为审计和诊断', provides: ['eventLog'], inject: [], keywords: ['event', 'log', 'audit'], category: 'core', tags: ['provider', 'infra'], hot: true, icon: '📋', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后系统行为日志不可用，故障排查困难' },
    { name: '@codem/telemetry', version: '1.0.0', description: 'Telemetry Provider — 遥测数据收集，使用量统计和性能监控', provides: ['telemetry'], inject: [], keywords: ['telemetry', 'metrics'], category: 'core', tags: ['provider', 'infra'], hot: true, icon: '📊', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后遥测数据不收集' },
    { name: '@codem/security-mode', version: '1.0.0', description: 'Security Mode Provider — 安全模式管理，沙箱策略和执行限制', provides: ['securityMode'], inject: [], keywords: ['security', 'mode', 'sandbox'], category: 'core', tags: ['provider', 'security'], hot: true, icon: '🔒', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后安全模式不可用，执行限制策略失效' },
    { name: '@codem/file-change-tracker', version: '1.0.0', description: 'File Change Tracker Provider — 文件变更追踪，编辑历史和差异记录', provides: ['fileChangeTracker'], inject: [], keywords: ['file', 'change', 'tracker'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '📝', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后文件变更追踪不可用' },
    { name: '@codem/transcript-cache', version: '1.0.0', description: 'Transcript Cache Provider — 会话缓存，快速恢复最近对话', provides: ['transcriptCache'], inject: [], keywords: ['transcript', 'cache'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '🗂️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后会话缓存不可用，恢复对话变慢' },
    { name: '@codem/agent-engine', version: '1.0.0', description: 'Agent Engine Provider — Agent 引擎核心，管理 Agent 生命周期和调度', provides: ['agentEngine'], inject: [], keywords: ['agent', 'engine'], category: 'core', tags: ['provider', 'agent'], hot: true, icon: '🧩', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后 Agent 引擎不可用，无法创建或运行 Agent' },
    { name: '@codem/i18n', version: '1.0.0', description: 'I18n Provider — 国际化服务，多语言支持', provides: ['i18n'], inject: [], keywords: ['i18n', 'locale', 'lang'], category: 'core', tags: ['provider', 'infra'], hot: true, icon: '🌐', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后国际化不可用，界面语言无法切换' },

    // ===== R5 Providers (从模块级单例升级为 Cordis 服务) =====
    { name: '@codem/cost-tracker', version: '1.0.0', description: 'Cost Tracker Provider — 成本追踪，API 调用费用统计', provides: ['costTracker'], inject: [], keywords: ['cost', 'tracker', 'billing'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '💰', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后费用统计不可用' },
    { name: '@codem/model-profile', version: '1.0.0', description: 'Model Profile Provider — 模型配置管理，模型参数和预设', provides: ['modelProfile'], inject: [], keywords: ['model', 'profile', 'config'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '⚙️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后模型配置不可用，使用默认参数' },
    { name: '@codem/streaming-executor', version: '1.0.0', description: 'Streaming Executor Provider — 流式执行器，管理 Agent 执行流', provides: ['streamingExecutor'], inject: [], keywords: ['streaming', 'executor'], category: 'core', tags: ['provider', 'runtime'], hot: true, icon: '🌊', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后流式执行不可用，Agent 无法流式输出' },
    { name: '@codem/tool-render', version: '1.0.0', description: 'Tool Render Provider — 工具渲染器，工具调用结果的 UI 渲染', provides: ['toolRender'], inject: [], keywords: ['tool', 'render'], category: 'provider', tags: ['provider', 'ui'], hot: true, icon: '🎨', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后工具调用结果不渲染 UI' },
    { name: '@codem/agent-registry', version: '1.0.0', description: 'Agent Registry Provider — Agent 注册表，管理已注册的 Agent', provides: ['agentRegistry'], inject: [], keywords: ['agent', 'registry'], category: 'core', tags: ['provider', 'agent'], hot: true, icon: '📚', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后 Agent 注册表不可用' },
    { name: '@codem/recovery', version: '1.0.0', description: 'Recovery Provider — 恢复服务，快照保存和恢复点管理', provides: ['recovery'], inject: [], keywords: ['recovery', 'snapshot', 'checkpoint'], category: 'core', tags: ['provider', 'storage'], hot: true, icon: '🔄', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后恢复点不可用，系统故障后无法恢复' },
    { name: '@codem/retry', version: '1.0.0', description: 'Retry Provider — 重试服务，失败操作的自动重试和退避', provides: ['retry'], inject: [], keywords: ['retry', 'backoff'], category: 'core', tags: ['provider', 'runtime'], hot: true, icon: '🔁', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后自动重试不可用，失败操作直接报错' },
    { name: '@codem/squad-manager', version: '1.0.0', description: 'Squad Manager Provider — 多 Agent 团队管理，Agent 编排和协作', provides: ['squadManager'], inject: [], keywords: ['squad', 'manager', 'orchestration'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '👥', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后多 Agent 团队管理不可用' },
    { name: '@codem/issue', version: '1.0.0', description: 'Issue Provider — 问题追踪服务，Bug 报告和任务管理', provides: ['issue'], inject: [], keywords: ['issue', 'bug', 'track'], category: 'provider', tags: ['provider'], hot: true, icon: '🐛', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后问题追踪不可用' },
    { name: '@codem/inbox', version: '1.0.0', description: 'Inbox Provider — 收件箱服务，消息队列和通知管理', provides: ['inbox'], inject: [], keywords: ['inbox', 'message', 'queue'], category: 'provider', tags: ['provider'], hot: true, icon: '📥', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后收件箱不可用' },

    // ===== R6: Zustand Store Cordis 服务化 =====
    { name: '@codem/store', version: '1.0.0', description: 'Zustand Store Provider — 全局状态管理服务，应用状态的中心枢纽', provides: ['appStore'], inject: [], keywords: ['store', 'zustand', 'state'], category: 'core', tags: ['provider', 'infra'], hot: true, icon: '🗃️', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后全局状态管理不可用，所有状态操作失败' },

    // ===== P1-7.4: LLM Provider 插件 =====
    { name: '@codem/llm-mimo', version: '1.0.0', description: 'LLM MiMo Provider — MiMo 模型专用适配器，原生 API 调用', provides: ['llmMimo'], inject: ['llm'], keywords: ['llm', 'mimo', 'model'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🤖', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 MiMo 模型不可用，切换到其他 LLM Provider' },
    { name: '@codem/llm-openai', version: '1.0.0', description: 'LLM OpenAI Provider — OpenAI 兼容模型适配器，支持 GPT/o1 等模型', provides: ['llmOpenAI'], inject: ['llm'], keywords: ['llm', 'openai', 'gpt'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🔮', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 OpenAI 兼容模型不可用' },
    { name: '@codem/llm-retry', version: '1.0.0', description: 'LLM Retry Provider — LLM 调用重试策略，指数退避和错误恢复', provides: ['llmRetry'], inject: ['llm'], keywords: ['llm', 'retry', 'backoff'], category: 'provider', tags: ['provider', 'runtime'], hot: true, icon: '🔄', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后 LLM 调用失败不自动重试' },
    { name: '@codem/token-meter', version: '1.0.0', description: 'Token Meter Provider — Token 计量服务，使用量统计和预算控制', provides: ['tokenMeter'], inject: [], keywords: ['token', 'meter', 'usage'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '🎯', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Token 计量不可用' },

    // ===== P1-7.5: 会话层插件 =====
    { name: '@codem/session-persistence-sqlite', version: '1.0.0', description: 'Session Persistence SQLite Provider — SQLite 持久化存储，会话历史本地保存', provides: ['sessionPersistence'], inject: ['session'], keywords: ['session', 'persistence', 'sqlite'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '💾', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后会话持久化不可用，重启后丢失历史' },
    { name: '@codem/session-projection', version: '1.0.0', description: 'Session Projection Provider — 会话投影，消息索引和快速查询', provides: ['sessionProjection'], inject: ['session'], keywords: ['session', 'projection', 'index'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '🔍', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后会话投影不可用，查询变慢' },
    { name: '@codem/session-stats', version: '1.0.0', description: 'Session Stats Provider — 会话统计，Token 使用和交互次数统计', provides: ['sessionStats'], inject: ['session'], keywords: ['session', 'stats', 'analytics'], category: 'provider', tags: ['provider'], hot: true, icon: '📈', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后会话统计不可用' },
    { name: '@codem/session-title-llm', version: '1.0.0', description: 'Session Title LLM Provider — LLM 生成会话标题，自动摘要对话主题', provides: ['sessionTitleLLM'], inject: ['llm', 'session'], keywords: ['session', 'title', 'llm'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🏷️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后会话标题不自动生成' },
    { name: '@codem/session-checkpoint', version: '1.0.0', description: 'Session Checkpoint Provider — 会话检查点，状态快照和回滚', provides: ['sessionCheckpoint'], inject: ['session'], keywords: ['session', 'checkpoint', 'snapshot'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '📌', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后会话检查点不可用' },

    // ===== P1-7.6: Shell/终端插件 =====
    { name: '@codem/pwsh-local', version: '1.0.0', description: 'PowerShell Local Provider — Windows PowerShell 本地执行', provides: ['pwshLocal'], inject: ['shell'], keywords: ['pwsh', 'powershell', 'windows'], category: 'provider', tags: ['provider', 'runtime'], hot: true, icon: '🖥️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 PowerShell 执行不可用' },
    { name: '@codem/bash-sandbox', version: '1.0.0', description: 'Bash Sandbox Provider — 沙箱内 Bash 执行，隔离环境命令运行', provides: ['bashSandbox'], inject: ['shell', 'sandbox'], keywords: ['bash', 'sandbox', 'shell'], category: 'provider', tags: ['provider', 'runtime', 'security'], hot: true, icon: '📦', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后沙箱 Bash 不可用' },
    { name: '@codem/terminal-bash', version: '1.0.0', description: 'Terminal Bash Provider — 终端 Bash 执行，原生 Shell 交互', provides: ['terminalBash'], inject: ['shell'], keywords: ['terminal', 'bash', 'shell'], category: 'provider', tags: ['provider', 'runtime'], hot: true, icon: '💻', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后终端 Bash 不可用' },

    // ===== P1-7.7: 沙箱/安全插件 =====
    { name: '@codem/sandbox-policy', version: '1.0.0', description: 'Sandbox Policy Provider — 沙箱策略管理，文件系统和网络访问控制', provides: ['sandboxPolicy'], inject: ['sandbox'], keywords: ['sandbox', 'policy', 'security'], category: 'provider', tags: ['provider', 'security'], hot: true, icon: '🛡️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后沙箱策略不可用' },
    { name: '@codem/subprocess', version: '1.0.0', description: 'Subprocess Provider — 子进程管理，进程创建和生命周期控制', provides: ['subprocess'], inject: [], keywords: ['subprocess', 'process', 'spawn'], category: 'provider', tags: ['provider', 'runtime'], hot: true, icon: '⚙️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后子进程管理不可用' },

    // ===== P1-7.8: 子 Agent 插件 =====
    { name: '@codem/subagent-fork-in-process', version: '1.0.0', description: 'Subagent Fork In-Process Provider — 进程内 Fork 子 Agent，轻量级 Agent 分叉', provides: ['subagentForkInProcess'], inject: ['subagent'], keywords: ['subagent', 'fork', 'in-process'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🔱', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后进程内 Fork 子 Agent 不可用' },
    { name: '@codem/subagent-spawn-in-process', version: '1.0.0', description: 'Subagent Spawn In-Process Provider — 进程内 Spawn 子 Agent，独立 Agent 实例', provides: ['subagentSpawnInProcess'], inject: ['subagent'], keywords: ['subagent', 'spawn', 'in-process'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🥚', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后进程内 Spawn 子 Agent 不可用' },
    { name: '@codem/subagent-control', version: '1.0.0', description: 'Subagent Control Provider — 子 Agent 控制工具，启动/停止/查询子 Agent 状态', provides: ['subagentControl'], inject: ['subagent'], keywords: ['subagent', 'control', 'tool'], category: 'provider', tags: ['provider', 'agent', 'tool'], hot: true, icon: '🎛️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后子 Agent 控制不可用' },

    // ===== P1-7.9: 上下文/压缩插件 =====
    { name: '@codem/compaction-basic', version: '1.0.0', description: 'Compaction Basic Provider — 基础压缩策略，摘要式上下文裁剪', provides: ['compactionBasic'], inject: ['compaction'], keywords: ['compaction', 'basic', 'summarize'], category: 'provider', tags: ['provider'], hot: true, icon: '✂️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后基础压缩策略不可用' },
    { name: '@codem/compaction-tool-result-pruner', version: '1.0.0', description: 'Compaction Tool Result Pruner Provider — 工具结果裁剪，长输出截断和摘要', provides: ['compactionToolResultPruner'], inject: ['compaction'], keywords: ['compaction', 'pruner', 'tool-result'], category: 'provider', tags: ['provider'], hot: true, icon: '🔨', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后工具结果裁剪不可用' },
    { name: '@codem/command-compact', version: '1.0.0', description: 'Command Compact Provider — /compact 命令，手动触发上下文压缩', provides: ['commandCompact'], inject: ['compaction', 'commands'], keywords: ['command', 'compact', 'manual'], category: 'provider', tags: ['provider', 'tool'], hot: true, icon: '⌘', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 /compact 命令不可用' },

    // ===== P1-7.10: 目标/计划/工作流插件 =====
    { name: '@codem/goal-round-driver', version: '1.0.0', description: 'Goal Round Driver Provider — 目标轮次驱动器，Agent 目标管理和迭代推进', provides: ['goalRoundDriver'], inject: [], keywords: ['goal', 'round', 'driver'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🎯', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后目标驱动器不可用' },
    { name: '@codem/command-goal', version: '1.0.0', description: 'Command Goal Provider — /goal 命令，设置和管理 Agent 目标', provides: ['commandGoal'], inject: ['commands'], keywords: ['command', 'goal'], category: 'provider', tags: ['provider', 'tool'], hot: true, icon: '🏁', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 /goal 命令不可用' },
    { name: '@codem/plan-mode', version: '1.0.0', description: 'Plan Mode Provider — 计划模式，结构化任务分解和步骤跟踪', provides: ['planMode'], inject: ['plans'], keywords: ['plan', 'mode', 'steps'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '📋', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后计划模式不可用' },

    // ===== P2-7.11: Web/搜索插件 =====
    { name: '@codem/web-fetch-http', version: '1.0.0', description: 'Web Fetch HTTP Provider — HTTP 网页抓取，HTML 转 Markdown', provides: ['webFetchHttp'], inject: ['web'], keywords: ['web', 'fetch', 'http'], category: 'provider', tags: ['provider'], hot: true, icon: '🌐', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后网页抓取不可用' },
    { name: '@codem/web-search-mimo', version: '1.0.0', description: 'Web Search MiMo Provider — MiMo 搜索引擎，专用搜索服务', provides: ['webSearchMimo'], inject: ['web'], keywords: ['web', 'search', 'mimo'], category: 'provider', tags: ['provider'], hot: true, icon: '🔎', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 MiMo 搜索不可用' },

    // ===== P2-7.12: Guard/保护插件 =====
    { name: '@codem/repeat-tool-reminder', version: '1.0.0', description: 'Repeat Tool Reminder Provider — 重复工具调用检测，防止 Agent 陷入循环', provides: ['repeatToolReminder'], inject: ['guard'], keywords: ['repeat', 'tool', 'reminder'], category: 'provider', tags: ['provider', 'security'], hot: true, icon: '🔁', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后重复调用检测不可用' },
    { name: '@codem/timeout-guard', version: '1.0.0', description: 'Timeout Guard Provider — 超时保护，工具调用和 LLM 请求的时间限制', provides: ['timeoutGuard'], inject: ['guard'], keywords: ['timeout', 'guard'], category: 'provider', tags: ['provider', 'security'], hot: true, icon: '⏱️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后超时保护不可用' },
    { name: '@codem/invariants-guard', version: '1.0.0', description: 'Invariants Guard Provider — 不变式检查，系统状态约束验证', provides: ['invariantsGuard'], inject: ['guard'], keywords: ['invariants', 'guard', 'check'], category: 'provider', tags: ['provider', 'security'], hot: true, icon: '✅', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后不变式检查不可用' },

    // ===== P2-7.13: Host/Client 架构插件 =====
    { name: '@codem/host-webserver', version: '1.0.0', description: 'Host Webserver Provider — Web 服务器，HTTP/WebSocket 接口', provides: ['hostWebserver'], inject: ['hostClient'], keywords: ['host', 'webserver', 'http'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '🖥️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Web 服务器不可用' },
    { name: '@codem/host-plugin-inventory', version: '1.0.0', description: 'Host Plugin Inventory Provider — 插件清单管理，已安装插件索引', provides: ['hostPluginInventory'], inject: ['hostClient'], keywords: ['host', 'plugin', 'inventory'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '📦', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后插件清单不可用' },
    { name: '@codem/sdk-protocol', version: '1.0.0', description: 'SDK Protocol Provider — SDK 协议层，外部程序调用接口', provides: ['sdkProtocol'], inject: ['hostClient'], keywords: ['sdk', 'protocol', 'api'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '🔌', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 SDK 协议不可用' },

    // ===== P2-7.14: UI 原语和面板插件 =====
    { name: '@codem/ui-primitives', version: '1.0.0', description: 'UI Primitives Provider — UI 原语服务，基础 UI 组件注册', provides: ['uiPrimitives'], inject: [], keywords: ['ui', 'primitives', 'components'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '🧱', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后基础 UI 组件不可用' , uiImpact: { panels: ["ui-components"], degradedTo: '基础 UI 组件不可用' }},
    { name: '@codem/ui-input-trigger', version: '1.0.0', description: 'UI Input Trigger Provider — 输入触发器，快捷输入和命令补全', provides: ['uiInputTrigger'], inject: [], keywords: ['ui', 'input', 'trigger'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '⌨️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后输入触发器不可用' , uiImpact: { panels: ["input-trigger"], degradedTo: '输入触发器不可用' }},
    { name: '@codem/ui-agent-preset', version: '1.0.0', description: 'UI Agent Preset Provider — Agent 预设面板，预设选择和切换 UI', provides: ['uiAgentPreset'], inject: [], keywords: ['ui', 'agent', 'preset'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '🎭', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Agent 预设面板不可用' , uiImpact: { panels: ["agent-preset"], degradedTo: 'Agent 预设面板不可用' }},
    { name: '@codem/ui-skill-panel', version: '1.0.0', description: 'UI Skill Panel Provider — 技能面板 UI，技能管理和展示', provides: ['uiSkillPanel'], inject: [], keywords: ['ui', 'skill', 'panel'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '⚡', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后技能面板不可用' , uiImpact: { panels: ["skill-panel"], degradedTo: '技能面板不可用' }},

    // ===== P2-7.15: Typert 类型系统插件 =====
    { name: '@codem/typert-generator', version: '1.0.0', description: 'Typert Generator Provider — 类型生成器，自动生成 TypeScript 类型定义', provides: ['typertGenerator'], inject: [], keywords: ['typert', 'generator', 'types'], category: 'provider', tags: ['provider', 'tool'], hot: true, icon: '🔧', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后类型生成不可用' },
    { name: '@codem/typert-loader', version: '1.0.0', description: 'Typert Loader Provider — 类型加载器，运行时类型解析和加载', provides: ['typertLoader'], inject: [], keywords: ['typert', 'loader', 'types'], category: 'provider', tags: ['provider', 'tool'], hot: true, icon: '📥', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后类型加载不可用' },
    { name: '@codem/typert-protocol', version: '1.0.0', description: 'Typert Protocol Provider — 类型协议，类型序列化和通信协议', provides: ['typertProtocol'], inject: [], keywords: ['typert', 'protocol', 'serialization'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '📡', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后类型协议不可用' },
    { name: '@codem/typert-registry', version: '1.0.0', description: 'Typert Registry Provider — 类型注册表，全局类型定义管理', provides: ['typertRegistry'], inject: [], keywords: ['typert', 'registry', 'types'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '📚', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后类型注册表不可用' },

    // ===== R7-1: 缺失 LLM 多模型适配器 =====
    { name: '@codem/llm-claude', version: '1.0.0', description: 'LLM Claude Provider — Anthropic Claude 3.5 模型适配器', provides: ['llmClaude'], inject: ['llm'], keywords: ['llm', 'claude', 'anthropic'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🧠', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Claude 模型不可用' },
    { name: '@codem/llm-gemini', version: '1.0.0', description: 'LLM Gemini Provider — Google Gemini 1.5 Pro/Flash 模型适配器', provides: ['llmGemini'], inject: ['llm'], keywords: ['llm', 'gemini', 'google'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '💎', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Gemini 模型不可用' },
    { name: '@codem/llm-ollama', version: '1.0.0', description: 'LLM Ollama Provider — 本地 Ollama 模型适配器，支持 Llama/Qwen/DeepSeek', provides: ['llmOllama'], inject: ['llm'], keywords: ['llm', 'ollama', 'local', 'offline'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🖥️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后本地模型不可用' },

    // ===== R7-2: 会话恢复插件 =====
    { name: '@codem/session-recovery', version: '1.0.0', description: 'Session Recovery Provider — 会话崩溃恢复，自动保存和恢复上下文快照', provides: ['sessionRecovery'], inject: ['session'], keywords: ['session', 'recovery', 'crash', 'restore'], category: 'core', tags: ['provider', 'storage'], hot: true, icon: '🔄', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后崩溃恢复不可用，异常退出后丢失会话' },

    // ===== R7-3: 缺失 UI 组件插件 =====
    { name: '@codem/ui-directory-picker', version: '1.0.0', description: 'UI Directory Picker Provider — 目录选择器组件，支持原生和浏览器模式', provides: ['uiDirectoryPicker'], inject: [], keywords: ['ui', 'directory', 'picker'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '📂', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后目录选择器不可用' , uiImpact: { panels: ["directory-picker"], degradedTo: '目录选择器不可用' }},
    { name: '@codem/ui-message-feedback', version: '1.0.0', description: 'UI Message Feedback Provider — 消息反馈组件，点赞/点踩/评论', provides: ['uiMessageFeedback'], inject: [], keywords: ['ui', 'feedback', 'message'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '👍', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后消息反馈 UI 不可用' , uiImpact: { panels: ["message-feedback"], degradedTo: '消息反馈 UI 不可用' }},
    { name: '@codem/ui-model-selection', version: '1.0.0', description: 'UI Model Selection Provider — 模型选择器组件，模型列表和切换', provides: ['uiModelSelection'], inject: ['modelProfile'], keywords: ['ui', 'model', 'selection'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '🔀', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后模型选择 UI 不可用' , uiImpact: { panels: ["model-selection"], degradedTo: '模型选择器不可用' }},
    { name: '@codem/ui-permission-presets', version: '1.0.0', description: 'UI Permission Presets Provider — 权限预设管理，快速切换权限级别', provides: ['uiPermissionPresets'], inject: ['permission'], keywords: ['ui', 'permission', 'presets'], category: 'ui', tags: ['provider', 'ui', 'security'], hot: true, icon: '🔐', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后权限预设不可用' , uiImpact: { panels: ["permission-presets"], degradedTo: '权限预设不可用' }},
    { name: '@codem/ui-trajectory', version: '1.0.0', description: 'UI Trajectory Provider — 执行轨迹可视化，记录和展示 Agent 操作步骤', provides: ['uiTrajectory'], inject: [], keywords: ['ui', 'trajectory', 'steps'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '📊', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后执行轨迹不可用' , uiImpact: { panels: ["trajectory"], degradedTo: '执行轨迹不可用' }},
    { name: '@codem/ui-deliverables', version: '1.0.0', description: 'UI Deliverables Provider — 交付物管理，文件变更的接受/拒绝', provides: ['uiDeliverables'], inject: [], keywords: ['ui', 'deliverables', 'files'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '📦', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后交付物管理不可用' , uiImpact: { panels: ["deliverables"], degradedTo: '交付物管理不可用' }},

    // ===== R7-4: Host/Client 链路拆分 =====
    { name: '@codem/bundle', version: '1.0.0', description: 'Bundle Provider — 插件包管理（安装/卸载/列表），接入 PluginLoader', provides: ['bundle'], inject: [], keywords: ['bundle', 'install', 'plugin'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '📦', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后插件包管理不可用' },
    { name: '@codem/acp', version: '1.0.0', description: 'ACP Provider — 自动化控制协议，触发器和调度管理', provides: ['acp'], inject: ['automation'], keywords: ['acp', 'automation', 'trigger'], category: 'provider', tags: ['provider', 'automation'], hot: true, icon: '🤖', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后自动化触发不可用' },
    { name: '@codem/host', version: '1.0.0', description: 'Host Provider — 本地 Host 服务管理，启动/停止 Tauri sidecar 或 HTTP server', provides: ['host'], inject: ['hostWebserver'], keywords: ['host', 'server', 'sidecar'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '🖥️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Host 服务不可用' },
    { name: '@codem/remote-client', version: '1.0.0', description: 'Remote Client Provider — 远端客户端连接，WebSocket/HTTP 连接管理', provides: ['client'], inject: ['sdkProtocol'], keywords: ['client', 'remote', 'connect'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '🔗', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后远端连接不可用' },

    // ===== R7-7: CLI 入口插件 =====
    { name: '@codem/cli', version: '1.0.0', description: 'CLI Provider — 命令行入口，支持终端运行 Codem 命令', provides: ['cli'], inject: ['session', 'tools', 'pluginRegistry'], keywords: ['cli', 'command', 'terminal'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '⌨️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后命令行接口不可用' },

    // ===== R8: 78 个 DSH 缺失插件补全 =====
    { name: '@codem/agent-loop', version: '1.0.0', description: 'AgenticLoop 独立 Cordis 插件，Agent 推理循环引擎', provides: ['agentLoop'], inject: ['llm', 'tools', 'agentEngine'], keywords: ['agent', 'loop', 'engine'], category: 'core', tags: ['provider', 'agent'], hot: true, icon: '🔄', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后 Agent 推理循环不可用' },
    { name: '@codem/agent', version: '1.0.0', description: 'Agent 管理器，Agent 实例创建注册和生命周期管理', provides: ['agentManager'], inject: ['agentRegistry'], keywords: ['agent', 'manager'], category: 'core', tags: ['provider', 'agent'], hot: true, icon: '🤖', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后无法创建和管理 Agent 实例' },
    { name: '@codem/agent-default-model', version: '1.0.0', description: '默认模型选择策略，根据任务类型自动选择最佳模型', provides: ['agentDefaultModel'], inject: ['modelProfile'], keywords: ['agent', 'default', 'model'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🎯', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后使用硬编码默认模型' },
    { name: '@codem/agent-tool-presentation', version: '1.0.0', description: '工具结果展示策略，格式化工具调用输出', provides: ['agentToolPresentation'], inject: ['toolRender'], keywords: ['agent', 'tool', 'presentation'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🎨', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后工具结果使用默认格式展示' },
    { name: '@codem/agent-instructions', version: '1.0.0', description: 'Agent 指令上下文，系统级指令注入和管理', provides: ['agentInstructions'], inject: [], keywords: ['agent', 'instructions', 'context'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '📜', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后 Agent 指令注入不可用' },
    { name: '@codem/system-prompt', version: '1.0.0', description: '系统提示词插件化组装，支持多段拼接和动态注入', provides: ['systemPrompt'], inject: ['agentInstructions'], keywords: ['system', 'prompt', 'assembly'], category: 'core', tags: ['provider', 'agent'], hot: true, icon: '📝', author: 'Codem Team', riskLevel: 'danger', riskDescription: '关闭后系统提示词不组装' },
    { name: '@codem/scope', version: '1.0.0', description: '多 Scope 上下文隔离，不同 Agent/会话的上下文隔离管理', provides: ['scope'], inject: [], keywords: ['scope', 'context', 'isolation'], category: 'core', tags: ['provider', 'agent'], hot: true, icon: '🔲', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后多 Scope 隔离不可用' },
    { name: '@codem/session-persistence-jsonl', version: '1.0.0', description: 'JSONL 格式会话持久化，追加写入高性能', provides: ['sessionPersistenceJSONL'], inject: ['session'], keywords: ['session', 'persistence', 'jsonl'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '📄', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后 JSONL 持久化不可用' },
    { name: '@codem/session-projection-cache', version: '1.0.0', description: '会话投影缓存，热数据内存索引加速查询', provides: ['sessionProjectionCache'], inject: ['sessionProjection'], keywords: ['session', 'projection', 'cache'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '⚡', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后投影缓存不可用' },
    { name: '@codem/session-query-sqlite', version: '1.0.0', description: 'SQLite 会话查询引擎，复杂条件检索和分页', provides: ['sessionQuerySqlite'], inject: ['session'], keywords: ['session', 'query', 'sqlite'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '🔍', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后高级会话查询不可用' },
    { name: '@codem/session-log-export', version: '1.0.0', description: '会话日志导出，支持 JSON/Markdown/HTML 格式', provides: ['sessionLogExport'], inject: ['session'], keywords: ['session', 'log', 'export'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '📤', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后日志导出不可用' },
    { name: '@codem/session-reference', version: '1.0.0', description: '会话交叉引用，消息间引用关系管理', provides: ['sessionReference'], inject: ['session'], keywords: ['session', 'reference', 'cross-reference'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '🔗', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后消息引用关系不可追踪' },
    { name: '@codem/session-telemetry-otel', version: '1.0.0', description: 'OpenTelemetry 遥测，分布式追踪和指标收集', provides: ['sessionTelemetryOtel'], inject: ['telemetry'], keywords: ['session', 'telemetry', 'otel'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '📊', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 OTel 遥测不收集' },
    { name: '@codem/session-title-first-prompt-llm', version: '1.0.0', description: '首条提示词生成会话标题，快速命名', provides: ['sessionTitleFirstPrompt'], inject: ['llm', 'session'], keywords: ['session', 'title', 'first-prompt'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🏷️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后首条提示词标题不可用' },
    { name: '@codem/session-title-all-prompts-llm', version: '1.0.0', description: '所有提示词综合生成会话标题，全局摘要', provides: ['sessionTitleAllPrompts'], inject: ['llm', 'session'], keywords: ['session', 'title', 'all-prompts'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🏷️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后全局摘要标题不可用' },
    { name: '@codem/session-checkpoint-policy', version: '1.0.0', description: '检查点策略管理，频率触发条件保留策略', provides: ['sessionCheckpointPolicy'], inject: ['sessionCheckpoint'], keywords: ['session', 'checkpoint', 'policy'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '📌', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后检查点策略不可用' },
    { name: '@codem/pwsh-sandbox', version: '1.0.0', description: '沙箱内 PowerShell 执行，隔离环境命令运行', provides: ['pwshSandbox'], inject: ['shell', 'sandbox'], keywords: ['pwsh', 'sandbox'], category: 'provider', tags: ['provider', 'runtime', 'security'], hot: true, icon: '🔒', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后沙箱 PowerShell 不可用' },
    { name: '@codem/tool-bash-persistent', version: '1.0.0', description: '持久化 Bash 会话，跨工具调用保持工作目录和环境', provides: ['toolBashPersistent'], inject: ['shell'], keywords: ['bash', 'persistent'], category: 'provider', tags: ['provider', 'runtime'], hot: true, icon: '💬', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后 Bash 会话不持久化' },
    { name: '@codem/tmux-context', version: '1.0.0', description: 'Tmux 上下文管理，终端会话复用和窗口管理', provides: ['tmuxContext'], inject: ['shell'], keywords: ['tmux', 'context', 'terminal'], category: 'provider', tags: ['provider', 'runtime'], hot: true, icon: '🖥️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Tmux 上下文不可用' },
    { name: '@codem/fs-observation-policy', version: '1.0.0', description: '文件观察策略，监控变更的频率和范围控制', provides: ['fsObservationPolicy'], inject: [], keywords: ['fs', 'observation', 'policy'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '👁️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后文件观察策略不可用' },
    { name: '@codem/fs-sandbox', version: '1.0.0', description: '沙箱文件系统，隔离的虚拟文件系统操作', provides: ['fsSandbox'], inject: ['fs', 'sandbox'], keywords: ['fs', 'sandbox', 'virtual'], category: 'provider', tags: ['provider', 'storage', 'security'], hot: true, icon: '📦', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后沙箱文件系统不可用' },
    { name: '@codem/tool-fs-search', version: '1.0.0', description: '文件搜索工具，独立插件形式的文件内容名称搜索', provides: ['toolFsSearch'], inject: ['fs', 'tools'], keywords: ['tool', 'fs', 'search'], category: 'provider', tags: ['provider', 'tool'], hot: true, icon: '🔎', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后文件搜索工具不可用' },
    { name: '@codem/tool-str-replace-editor', version: '1.0.0', description: '字符串替换编辑器工具，精确查找替换文件内容', provides: ['toolStrReplaceEditor'], inject: ['fs', 'tools'], keywords: ['tool', 'str', 'replace', 'editor'], category: 'provider', tags: ['provider', 'tool'], hot: true, icon: '✏️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后字符串替换编辑器不可用' },
    { name: '@codem/sandbox-windows-acl', version: '1.0.0', description: 'Windows ACL 沙箱，基于访问控制列表的权限隔离', provides: ['sandboxWindowsAcl'], inject: ['sandbox'], keywords: ['sandbox', 'windows', 'acl'], category: 'provider', tags: ['provider', 'security'], hot: true, icon: '🪟', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后 Windows ACL 沙箱不可用' },
    { name: '@codem/e2b', version: '1.0.0', description: 'E2B 云沙箱，远程隔离代码执行环境', provides: ['e2b'], inject: [], keywords: ['e2b', 'cloud', 'sandbox'], category: 'provider', tags: ['provider', 'runtime', 'security'], hot: true, icon: '☁️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后 E2B 云沙箱不可用' },
    { name: '@codem/fs-e2b', version: '1.0.0', description: 'E2B 文件系统，远程沙箱文件操作', provides: ['fsE2b'], inject: ['e2b'], keywords: ['fs', 'e2b', 'remote'], category: 'provider', tags: ['provider', 'storage', 'security'], hot: true, icon: '📁', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后 E2B 文件系统不可用' },
    { name: '@codem/subprocess-e2b', version: '1.0.0', description: 'E2B 子进程，远程沙箱进程管理', provides: ['subprocessE2b'], inject: ['e2b', 'subprocess'], keywords: ['subprocess', 'e2b', 'remote'], category: 'provider', tags: ['provider', 'runtime', 'security'], hot: true, icon: '⚙️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后 E2B 子进程不可用' },
    { name: '@codem/subprocess-local', version: '1.0.0', description: '本地子进程管理，进程创建和生命周期控制', provides: ['subprocessLocal'], inject: ['subprocess'], keywords: ['subprocess', 'local', 'process'], category: 'provider', tags: ['provider', 'runtime'], hot: true, icon: '⚙️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后本地子进程管理不可用' },
    { name: '@codem/subagent-acp', version: '1.0.0', description: 'ACP 协议子 Agent，通过 ACP 协议编排子 Agent', provides: ['subagentAcp'], inject: ['subagent', 'acp'], keywords: ['subagent', 'acp'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🔗', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 ACP 子 Agent 不可用' },
    { name: '@codem/subagent-claude-code', version: '1.0.0', description: 'Claude Code 子 Agent，通过 Claude Code SDK 创建子 Agent', provides: ['subagentClaudeCode'], inject: ['subagent', 'llm'], keywords: ['subagent', 'claude', 'code'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🧠', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Claude Code 子 Agent 不可用' },
    { name: '@codem/subagent-codex', version: '1.0.0', description: 'Codex 子 Agent，通过 Codex 协议创建子 Agent', provides: ['subagentCodex'], inject: ['subagent', 'llm'], keywords: ['subagent', 'codex'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '📝', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Codex 子 Agent 不可用' },
    { name: '@codem/subagent-dsh-sdk', version: '1.0.0', description: 'DSH SDK 子 Agent，通过 DSH SDK 创建子 Agent', provides: ['subagentDshSdk'], inject: ['subagent', 'sdkProtocol'], keywords: ['subagent', 'dsh', 'sdk'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🔗', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 DSH SDK 子 Agent 不可用' },
    { name: '@codem/subagent-in-process-driver', version: '1.0.0', description: '进程内子 Agent 驱动，管理子 Agent 生命周期和调度', provides: ['subagentInProcessDriver'], inject: ['subagent'], keywords: ['subagent', 'in-process', 'driver'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🚗', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后进程内子 Agent 驱动不可用' },
    { name: '@codem/tool-subagent-report', version: '1.0.0', description: '子 Agent 报告工具，收集和汇总子 Agent 执行结果', provides: ['toolSubagentReport'], inject: ['subagent'], keywords: ['tool', 'subagent', 'report'], category: 'provider', tags: ['provider', 'agent', 'tool'], hot: true, icon: '📋', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后子 Agent 报告工具不可用' },
    { name: '@codem/llm-deepseek', version: '1.0.0', description: 'DeepSeek 原生 API Provider，支持 DeepSeek Chat/Coder/V3', provides: ['llmDeepseek'], inject: ['llm'], keywords: ['llm', 'deepseek'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🐉', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 DeepSeek 模型不可用' },
    { name: '@codem/llm-pi-ai', version: '1.0.0', description: 'Pi AI LLM Provider，Inflection Pi 模型适配器', provides: ['llmPiAi'], inject: ['llm'], keywords: ['llm', 'pi', 'ai'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🥧', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Pi AI 模型不可用' },
    { name: '@codem/web-search-exa', version: '1.0.0', description: 'Exa 搜索引擎 Provider，AI 优化搜索结果', provides: ['webSearchExa'], inject: ['web'], keywords: ['web', 'search', 'exa'], category: 'provider', tags: ['provider'], hot: true, icon: '🔎', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Exa 搜索不可用' },
    { name: '@codem/web-search-perplexity', version: '1.0.0', description: 'Perplexity 搜索 Provider，对话式 AI 搜索', provides: ['webSearchPerplexity'], inject: ['web'], keywords: ['web', 'search', 'perplexity'], category: 'provider', tags: ['provider'], hot: true, icon: '🔍', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Perplexity 搜索不可用' },
    { name: '@codem/time-context', version: '1.0.0', description: '时间上下文注入，给 Agent 感知当前时间和时区', provides: ['timeContext'], inject: [], keywords: ['time', 'context'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🕐', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后时间上下文注入不可用' },
    { name: '@codem/tool-ralph', version: '1.0.0', description: 'Ralph 工作流工具，迭代式代码审查和重构工作流', provides: ['toolRalph'], inject: ['workflow', 'tools'], keywords: ['tool', 'ralph', 'workflow'], category: 'provider', tags: ['provider', 'agent', 'tool'], hot: true, icon: '🔧', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Ralph 工作流工具不可用' },
    { name: '@codem/workflow-worker-thread', version: '1.0.0', description: 'Worker 线程工作流，多线程并行任务执行', provides: ['workflowWorkerThread'], inject: ['workflow'], keywords: ['workflow', 'worker', 'thread'], category: 'provider', tags: ['provider', 'runtime'], hot: true, icon: '🧵', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Worker 线程工作流不可用' },
    { name: '@codem/code-runtime-worker-thread', version: '1.0.0', description: 'Worker 线程代码运行时，隔离线程内执行代码', provides: ['codeRuntimeWorkerThread'], inject: ['codeRuntime'], keywords: ['code', 'runtime', 'worker'], category: 'provider', tags: ['provider', 'runtime'], hot: true, icon: '🏃', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Worker 线程代码运行时不可用' },
    { name: '@codem/spill', version: '1.0.0', description: '溢出管理，上下文超限时的分片策略', provides: ['spill'], inject: [], keywords: ['spill', 'overflow'], category: 'provider', tags: ['provider'], hot: true, icon: '💧', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后溢出管理不可用' },
    { name: '@codem/spill-local', version: '1.0.0', description: '本地溢出，溢出数据保存到本地存储', provides: ['spillLocal'], inject: ['spill'], keywords: ['spill', 'local'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '💾', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后本地溢出不可用' },
    { name: '@codem/spill-policy', version: '1.0.0', description: '溢出策略，溢出触发条件和保留策略管理', provides: ['spillPolicy'], inject: ['spill'], keywords: ['spill', 'policy'], category: 'provider', tags: ['provider'], hot: true, icon: '📋', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后溢出策略不可用' },
    { name: '@codem/tool-call-timeout-policy', version: '1.0.0', description: '工具调用超时策略，不同工具的超时配置', provides: ['toolCallTimeoutPolicy'], inject: ['timeoutGuard'], keywords: ['tool', 'timeout', 'policy'], category: 'provider', tags: ['provider', 'security'], hot: true, icon: '⏱️', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后工具调用超时策略不可用' },
    { name: '@codem/host-apiproxy', version: '1.0.0', description: 'API 代理，反向代理和请求转发', provides: ['hostApiproxy'], inject: ['hostWebserver'], keywords: ['host', 'api', 'proxy'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '🔀', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 API 代理不可用' },
    { name: '@codem/host-frontend-static', version: '1.0.0', description: '前端静态文件服务，HTTP 静态资源托管', provides: ['hostFrontendStatic'], inject: ['hostWebserver'], keywords: ['host', 'frontend', 'static'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '🌐', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后前端静态服务不可用' },
    { name: '@codem/sdk-client', version: '1.0.0', description: 'SDK 客户端，外部程序连接和调用接口', provides: ['sdkClient'], inject: ['sdkProtocol'], keywords: ['sdk', 'client'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '📲', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 SDK 客户端不可用' },
    { name: '@codem/api-gateway', version: '1.0.0', description: 'API 网关，统一入口路由和认证', provides: ['apiGateway'], inject: ['hostWebserver'], keywords: ['api', 'gateway'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '🚪', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 API 网关不可用' },
    { name: '@codem/api-remotes', version: '1.0.0', description: '远程 API，远程服务调用和管理', provides: ['apiRemotes'], inject: ['sdkProtocol'], keywords: ['api', 'remote'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '📡', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后远程 API 不可用' },
    { name: '@codem/ui-attachment', version: '1.0.0', description: '附件 UI 组件，文件上传和图片预览面板', provides: ['uiAttachment'], inject: ['slots'], keywords: ['ui', 'attachment'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '📎', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后附件 UI 不可用' , uiImpact: { slots: ["app.attachment"], degradedTo: '附件面板不显示' }},
    { name: '@codem/ui-cordis', version: '1.0.0', description: 'Cordis 管理面板，插件和服务状态查看', provides: ['uiCordis'], inject: ['slots'], keywords: ['ui', 'cordis'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '🧩', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Cordis 管理面板不可用' , uiImpact: { slots: ["app.cordis"], degradedTo: 'Cordis 管理面板不显示' }},
    { name: '@codem/ui-goal', version: '1.0.0', description: '目标面板 UI，Agent 目标设置和进度展示', provides: ['uiGoal'], inject: ['slots'], keywords: ['ui', 'goal'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '🎯', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后目标面板不可用' , uiImpact: { slots: ["app.goal"], degradedTo: '目标面板回退到 fallback' }},
    { name: '@codem/ui-jobs', version: '1.0.0', description: 'Jobs 面板 UI，后台任务和作业管理界面', provides: ['uiJobs'], inject: ['slots'], keywords: ['ui', 'jobs'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '📋', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Jobs 面板不可用' , uiImpact: { slots: ["app.jobs"], degradedTo: 'Jobs 面板回退到 fallback' }},
    { name: '@codem/ui-layout', version: '1.0.0', description: '布局管理面板，界面布局配置和调整', provides: ['uiLayout'], inject: ['slots'], keywords: ['ui', 'layout'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '📐', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后布局管理不可用' , uiImpact: { slots: ["app.layout"], degradedTo: '布局管理回退到 fallback' }},
    { name: '@codem/ui-plan', version: '1.0.0', description: '计划面板 UI，结构化任务计划和步骤跟踪界面', provides: ['uiPlan'], inject: ['slots'], keywords: ['ui', 'plan'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '📝', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后计划面板不可用' , uiImpact: { slots: ["app.plan"], degradedTo: '计划面板回退到 fallback' }},
    { name: '@codem/ui-settings-general', version: '1.0.0', description: '通用设置面板，全局配置界面', provides: ['uiSettingsGeneral'], inject: ['slots'], keywords: ['ui', 'settings', 'general'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '⚙️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后通用设置面板不可用' , uiImpact: { slots: ["app.settings.general"], degradedTo: '通用设置回退到 fallback' }},
    { name: '@codem/ui-settings-models', version: '1.0.0', description: '模型设置面板，LLM 模型配置界面', provides: ['uiSettingsModels'], inject: ['slots'], keywords: ['ui', 'settings', 'models'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '🔮', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后模型设置面板不可用' , uiImpact: { slots: ["app.settings.models"], degradedTo: '模型设置回退到 fallback' }},
    { name: '@codem/ui-settings-plugin-inventory', version: '1.0.0', description: '插件清单设置面板，已安装插件管理', provides: ['uiSettingsPluginInventory'], inject: ['slots'], keywords: ['ui', 'settings', 'plugins'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '📦', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后插件清单设置不可用' , uiImpact: { slots: ["app.plugin-market"], degradedTo: '插件清单不显示' }},
    { name: '@codem/ui-settings-plugins', version: '1.0.0', description: '插件设置面板，插件配置和开关管理', provides: ['uiSettingsPlugins'], inject: ['slots'], keywords: ['ui', 'settings', 'plugins'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '🔌', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后插件设置面板不可用' , uiImpact: { slots: ["app.settings.plugins"], degradedTo: '插件设置回退到 fallback' }},
    { name: '@codem/ui-slots', version: '1.0.0', description: 'Slot 管理面板，UI 槽位和插件注册查看', provides: ['uiSlots'], inject: ['slots'], keywords: ['ui', 'slots'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '🧩', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Slot 管理面板不可用' , uiImpact: { slots: ["app.plugin-manager"], degradedTo: 'Slot 管理面板不显示' }},
    { name: '@codem/ui-subagent', version: '1.0.0', description: '子 Agent 面板，子 Agent 状态和管理界面', provides: ['uiSubagent'], inject: ['slots'], keywords: ['ui', 'subagent'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '👥', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后子 Agent 面板不可用' , uiImpact: { slots: ["app.subagent"], degradedTo: '子 Agent 面板不显示' }},
    { name: '@codem/ui-user-questions', version: '1.0.0', description: '用户问题面板，Agent 向用户提问的交互界面', provides: ['uiUserQuestions'], inject: ['slots'], keywords: ['ui', 'questions'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '❓', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后用户问题面板不可用' , uiImpact: { slots: ["app.user-questions"], degradedTo: '用户问题面板不显示' }},
    { name: '@codem/ui-workflow-run', version: '1.0.0', description: '工作流运行面板，工作流执行状态和进度展示', provides: ['uiWorkflowRun'], inject: ['slots'], keywords: ['ui', 'workflow'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '🔄', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后工作流运行面板不可用' , uiImpact: { slots: ["app.workflow-run"], degradedTo: '工作流面板不显示' }},
    { name: '@codem/ui-workspace', version: '1.0.0', description: '工作区面板，文件和项目工作区管理界面', provides: ['uiWorkspace'], inject: ['slots'], keywords: ['ui', 'workspace'], category: 'ui', tags: ['provider', 'ui'], hot: true, icon: '📁', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后工作区面板不可用' , uiImpact: { slots: ["app.workspace"], degradedTo: '工作区面板回退到 fallback' }},
    { name: '@codem/lsp-stdio', version: '1.0.0', description: 'LSP stdio 传输，标准输入输出传输层适配', provides: ['lspStdio'], inject: ['lsp'], keywords: ['lsp', 'stdio', 'transport'], category: 'provider', tags: ['provider', 'tool'], hot: true, icon: '📄', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 LSP stdio 传输不可用' },
    { name: '@codem/atomic-write', version: '1.0.0', description: '原子写入文件，写入失败时保持原文件不变', provides: ['atomicWrite'], inject: ['fs'], keywords: ['atomic', 'write', 'file'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '⚛️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后原子写入不可用' },
    { name: '@codem/user-approval', version: '1.0.0', description: '用户审批流程，关键操作的完整审批工作流', provides: ['userApproval'], inject: ['approval'], keywords: ['user', 'approval', 'workflow'], category: 'provider', tags: ['provider', 'security'], hot: true, icon: '✅', author: 'Codem Team', riskLevel: 'caution', riskDescription: '关闭后用户审批流程不可用' },
    { name: '@codem/skill-badge', version: '1.0.0', description: '技能徽章，技能成就和展示系统', provides: ['skillBadge'], inject: ['skill'], keywords: ['skill', 'badge'], category: 'provider', tags: ['provider'], hot: true, icon: '🏅', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后技能徽章不可用' },
    { name: '@codem/skill-filesystem', version: '1.0.0', description: '技能文件系统，从文件系统加载技能定义', provides: ['skillFilesystem'], inject: ['skill', 'fs'], keywords: ['skill', 'filesystem'], category: 'provider', tags: ['provider'], hot: true, icon: '📁', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后技能文件系统不可用' },
    { name: '@codem/persona', version: '1.0.0', description: '人格管理，Agent 人格配置和行为风格切换', provides: ['persona'], inject: [], keywords: ['persona', 'personality'], category: 'provider', tags: ['provider', 'agent'], hot: true, icon: '🎭', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后人格管理不可用' },
    { name: '@codem/command-feedback', version: '1.0.0', description: '命令反馈，用户对 Agent 回复的反馈收集', provides: ['commandFeedback'], inject: [], keywords: ['command', 'feedback'], category: 'provider', tags: ['provider'], hot: true, icon: '💬', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后命令反馈不可用' },
    { name: '@codem/cordis-client-runner', version: '1.0.0', description: 'Cordis 客户端运行器，客户端 Cordis 实例管理', provides: ['cordisClientRunner'], inject: ['sdkClient'], keywords: ['cordis', 'client', 'runner'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '🏃', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Cordis 客户端运行器不可用' },
    { name: '@codem/cordis-host-runner', version: '1.0.0', description: 'Cordis Host 运行器，服务端 Cordis 实例管理', provides: ['cordisHostRunner'], inject: ['host'], keywords: ['cordis', 'host', 'runner'], category: 'provider', tags: ['provider', 'infra'], hot: true, icon: '🖥️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Cordis Host 运行器不可用' },
    { name: '@codem/tool-jobs', version: '1.0.0', description: 'Jobs 工具，独立插件形式的后台任务管理工具', provides: ['toolJobs'], inject: ['tools', 'automation'], keywords: ['tool', 'jobs'], category: 'provider', tags: ['provider', 'tool'], hot: true, icon: '📋', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 Jobs 工具不可用' },
    { name: '@codem/storage-domain', version: '1.0.0', description: '存储域定义，分域存储命名空间管理', provides: ['storageDomain'], inject: ['storage'], keywords: ['storage', 'domain', 'namespace'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '🗂️', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后存储域不可用' },
    { name: '@codem/storage-json', version: '1.0.0', description: 'JSON 存储后端，基于 JSON 文件的键值存储', provides: ['storageJson'], inject: ['storage'], keywords: ['storage', 'json'], category: 'provider', tags: ['provider', 'storage'], hot: true, icon: '📄', author: 'Codem Team', riskLevel: 'safe', riskDescription: '关闭后 JSON 存储后端不可用' },
    ]

/**
 * 运行时副本：模块加载时即填充，不依赖 fiber 激活。
 * PluginManager 在 ctx.get('pluginRegistry') 不可用时直接 import 使用。
 */
export const runtimePluginList: any[] = [...KNOWN_PLUGINS]

export const pluginRegistryProvider: Plugin = (ctx: any) => {
  const pluginMeta = new Map<string, any>()

  for (const p of KNOWN_PLUGINS) { pluginMeta.set(p.name, p) }

  const dispose = ctx.provide('pluginRegistry', {
    _active: true,
    register(meta: any) { pluginMeta.set(meta.name, meta) },
    unregister(name: string) { pluginMeta.delete(name) },
    get(name: string) { return pluginMeta.get(name) },
    search(query: string, limit: number = 20) {
      const q = query.toLowerCase()
      return [...pluginMeta.values()].filter(p =>
        p.name.toLowerCase().includes(q) || p.description.toLowerCase().includes(q) ||
        p.keywords?.some((k: string) => k.toLowerCase().includes(q))
      ).slice(0, limit)
    },
    list() { return [...pluginMeta.values()] },
    listByCapability(cap: string) { return [...pluginMeta.values()].filter(p => p.provides?.includes(cap) || p.inject?.includes(cap)) },
  })

  // Composite dispose
  const compositeDispose = () => {
    pluginMeta.clear()
    dispose()
  }
  return compositeDispose
}
